import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'dashboard',
    //     path: '/dashboard',
    //     title: 'Dashboard',
    //     translateKey: 'nav.dashboard',
    //     icon: 'graph',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'appsDefi.defi',
        path: '',
        title: 'Defi',
        translateKey: 'nav.defi',
        icon: 'sales',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'appsDefi.dashboard',
                path: `/defi/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.appsDefi.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsDefi.accounts',
                path: `/defi/accounts`,
                title: 'Accounts',
                translateKey: 'nav.appsDefi.accounts',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsDefi.transactions',
                path: `/defi/transactions`,
                title: 'Transactions',
                translateKey: 'nav.appsDefi.transactions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsDefi.protocols',
                path: `/defi/protocols`,
                title: 'Protocols',
                translateKey: 'nav.appsDefi.protocols',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appsDefi.balances',
                path: `/defi/balances`,
                title: 'Balances',
                translateKey: 'nav.appsDefi.balances',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'appsExchanges.exchanges',
        path: '',
        title: 'Exchanges',
        translateKey: 'nav.exchanges',
        icon: 'crm',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
          {
                key: 'appsExchanges.exchanges',
                path: `/exchanges/exchanges`,
                title: 'Exchanges',
                translateKey: 'nav.appsExchanges.exchanges',
                icon: 'crm',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            
            // {
            //     key: 'appsDefi.balances',
            //     path: `/defi/balances`,
            //     title: 'Balances',
            //     translateKey: 'nav.appsDefi.balances',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
        ],
    },
    {
        key: 'nav.teams',
        path: '',
        title: 'Teams',
        translateKey: 'nav.teams',
        icon: 'crm',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'team.list',
                path: `/teams`,
                title: 'Teams',
                translateKey: 'team.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'standardUsers.list',
                path: `/standard-users`,
                title: 'Users',
                translateKey: 'standardUsers.list',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'snapshots',
        path: '/snapshots',
        title: 'Snapshots',
        translateKey: 'nav.snapshots',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'appSettings.settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.settings',
        icon: 'setting',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'appSettings.accounts',
                path: '/settings/profile',
                title: 'Accounts',
                translateKey: 'nav.appSettings.accounts',
                icon: 'account',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appSettings.contacts',
                path: '/settings/contacts',
                title: 'Contacts',
                translateKey: 'nav.appSettings.contacts',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appSettings.contracts',
                path: '/settings/contracts',
                title: 'Contracts',
                translateKey: 'nav.appSettings.contracts',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
